name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  yamllint:
    name: yaml-lint
    runs-on: ubuntu-latest
    if: github.repository_owner == 'saydulaev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          format: github
          config_file: .yamllint

      - run: echo ${{ steps.yaml-lint.outputs.logfile }}
